swagger: '2.0'

info:
  version: "2.0.1"
  title: BP API
  
basePath: /api/v2
produces:
  - application/json

paths:

################################################################################
#                                   Users                                      #
################################################################################ 

  /user:
    post:
      summary: User Creation.
      description:
       Submit a Createuser object in order to creat a user in BrewPass
      parameters:
        - in: body
          name: body
          description: CreateUser Object
          required: true
          schema:
            $ref: "#/definitions/CreateUser"
      responses:
        "201":
          description: User Created
        "409":
          description: Account with that email already exists.
          
  /user/{userId}:
    get:
      summary: User Information
      description:
        User endpoint returns information about the user.
      parameters:
        - name: userId
          in: path
          description: ID of User
          required: true
          type: string
          format: string
      tags:
        - User
      responses:
        "200":
          description: A User object
          schema:
            $ref: '#/definitions/User'
        "404":
          description: User Not Found
    put:
      summary: User Modification
      parameters:
        - name: userId
          in: path
          description: ID of User
          required: true
          type: string
          format: string
        - in: body
          name: user
          description: User Object
          required: true
          schema:
            $ref: "#/definitions/User"
      tags:
        - User
      responses:
        "200":
          description: User Updated
        "404":
          description: User Not Found
    delete:
      summary: User Modification
      parameters:
      - name: userId
        in: path
        description: ID of User
        required: true
        type: string
        format: string
      tags:
        - User
      responses:
        "204":
          description: User Deleted
        "403":
          description: Not allowed to modify this User
        "404":
          description: User Not Found
          
  /user/{userId}/payment:
    post:
        summary: User Payment Method Creation.
        description:
         Add a credit card to a BrewPass User
        parameters:
          - name: userId
            in: path
            description: ID of User
            required: true
            type: string
            format: string
        tags:
          - User
          - Payment
        responses:
          "201":
            description:  User Created
            
  /user/{userId}/payment/{paymentId}:
     delete:
        summary: User Payment Method Deletion.
        description:
         Delete a method of payment from a User.
        parameters:
          - name: userId
            in: path
            description: Id of User to modify
            required: true
            type: string
            format: string
          - name: paymentId
            in: path
            description: Payment Id to Delete
            required: true
            type: string
            format: string
        tags:
          - User
          - Payment  
        responses:
          "201":
            description:  User Created

  /user/{id}/purchase:
    post:
      summary: Purchase For User
      parameters:
      - name: id
        in: path
        description: ID of User
        required: true
        type: string
        format: string
      - name: body
        in: body
        description: Request to process for purchase
        required: true
        schema: 
          $ref: '#/definitions/Purchase'
      tags:
        - User
        - Purchase 
      responses:
        "201":
          description:  Purchase Successful

  /user/{id}/subscriptions:
    post:
      summary: subscriptions For User
      parameters:
      - name: id
        in: path
        description: ID of User
        required: true
        type: string
      - name: body
        in: body
        description: Request to process for redemption
        required: true
        schema: 
          $ref: '#/definitions/Subscription'
      tags:
        - User
        - Subscription 
      responses:
        "201":
          description: Subscription added to User
        "400":
          description: Subscription not applicable to user. 
  
  /user/{userId}/subscriptions/{subscriptionId}:
    delete:
      summary: Cancel Subscription For User
      description: |
        Maintains current BrewPass subscription logic. If plan is more expensive, 
        take effect immediately, otherwise switch subscriptions after current 
        billing cycle. 
      parameters:
      - name: userId
        in: path
        description: ID of User
        required: true
        type: string
      - name: subscriptionId
        in: path
        description: ID of Location
        required: true
        type: string
        format: string
      tags:
        - User
        - Subscription 
      responses:
        "204":
          description: Subsciption set to Cancel
        "400":
          description: Subscription not applicable to user.

################################################################################
#                                 Location                                     #
################################################################################ 

  /location:
    post:
      summary: Location Creation.
      responses:
        "201":
          description:  Location Created

  /location/{id}:
    get:
      summary: Location Information
      description:
        Location endpoint returns information about the location.
      parameters:
        - name: id
          in: path
          description: Location
          required: true
          type: string
          format: string
      tags:
        - Location
      responses:
        "200":
          description: An Location object
          schema:
            $ref: '#/definitions/Location'
    put:
      summary: Location Modification
      parameters:
      - name: id
        in: path
        description: ID of Location
        required: true
        type: string
        format: string
      - in: body
        name: body
        description: Location Object
        required: true
        schema:
          $ref: "#/definitions/CreateUser"
      tags:
        - Location
      responses:
        "200":
          description: Location Updated
    delete:
      summary: Location Deletion
      parameters:
      - name: id
        in: path
        description: Id of Location to Delete
        required: true
        type: string
        format: string
      tags:
        - Location
      responses:
        "204":
          description: Location Deleted

################################################################################
#                               Location Items                                 #
################################################################################

  /location/{locationId}/items:
    post:
      summary: Item Creation.
      parameters:
        - name: locationId
          in: path
          description: Item
          required: true
          type: string
          format: string
      responses:
        "201":
          description:  Item Created
          schema:
            type: array
            title: itemIds
            $ref: '#/definitions/Item'

  /location/{locationId}/items/{id}:
    get:
      summary: Item Information
      description:
        The Item endpoint returns information about the item.
      parameters:
      - name: locationId
        in: path
        description: Item
        required: true
        type: string
        format: string
      - name: id
        in: path
        description: Item
        required: true
        type: string
        format: string
      tags:
        - Item
      responses:
        "200":
          description: Items available at location.
          schema:
            type: array
            items:
              type: string

    put:
      summary: Item Modification
      parameters:
      - name: locationId
        in: path
        description: Item
        required: true
        type: string
        format: string
      - name: id
        in: path
        description: Item
        required: true
        type: string
        format: string
      tags:
        - Item
      responses:
        "200":
          description: Item Updated
    delete:
      summary: Item Deletion
      parameters:
      - name: locationId
        in: path
        description: Item
        required: true
        type: string
        format: string
      - name: id
        in: path
        description: Item
        required: true
        type: string
        format: string
      tags:
        - Item
      responses:
        "204":
          description: Item Deleted

################################################################################
#                             Location AddOn                                   #
################################################################################

  /location/{locationId}/addons:
    get:
      summary: AddOns from a Location
      description:
        The AddOn endpoint returns information about the addons.
      parameters:
      - name: locationId
        in: path
        description: Item
        required: true
        type: string
        format: string
      responses:
        "201":
          description: AddOn Created
          schema:
            $ref: '#/definitions/AddOn'
    post:
      summary: AddOn Creation.
      parameters:
      - name: locationId
        in: path
        description: Item
        required: true
        type: string
        format: string
      responses:
        "201":
          description: AddOn Created
          schema:
            $ref: '#/definitions/AddOn'

  /location/{locationId}/addons/{id}:
    get:
      summary: AddOn Information
      description:
        The AddOn endpoint returns information about the addon.
      parameters:
      - name: locationId
        in: path
        description: Item
        required: true
        type: string
        format: string
      - name: id
        in: path
        description: Item
        required: true
        type: string
        format: string
      tags:
        - AddOn
      responses:
        "200":
          description: An AddOn object
          schema:
            $ref: '#/definitions/AddOn'
    put:
      summary: AddOn Modification
      parameters:
      - name: locationId
        in: path
        description: Item
        required: true
        type: string
        format: string
      - name: id
        in: path
        description: Item
        required: true
        type: string
        format: string
      tags:
        - AddOn
      responses:
        "200":
          description: AddOn Updated
    delete:
      summary: AddOn Deletion
      parameters:
      - name: locationId
        in: path
        description: Item
        required: true
        type: string
        format: string
      - name: id
        in: path
        description: Item
        required: true
        type: string
        format: string
      tags:
        - AddOn
      responses:
        "204":
          description: AddOn Deleted

################################################################################
#                                    Plan                                      #
################################################################################ 

  /plan:
    post:
      summary: Plan Creation
      parameters:
      - name: plan
        in: body
        description: Plan Information
        required: true
        schema:
            $ref: "#/definitions/Plan"
      responses:
        "201":
          description: Plan Created
        "409":
          description: Plan with that name already exists

  /plan/{planId}:
    get:
      summary: Plan Information
      description:
        The Plan endpoint returns information about the plan.
      parameters:
        - name: planId
          in: path
          description: Plan
          required: true
          type: string
          format: string
      tags:
        - Plan
      responses:
        "200":
          description: An Plan object
          schema:
            $ref: '#/definitions/Plan'
    put:
      summary: Plan Modification
      parameters:
      - name: planId
        in: path
        description: ID of Plan
        required: true
        type: string
        format: string
      tags:
        - Plan
      responses:
        "200":
          description: Plan Updated
    delete:
      summary: Plan Deletion
      parameters:
      - name: planId
        in: path
        description: ID of Plan
        required: true
        type: string
        format: string
      tags:
        - Plan
      responses:
        "204":
          description: Plan Deleted

  /plan/{planId}/items/{itemId}:
    post:
      summary: Single Plan Item Addition
      parameters:
      - name: planId
        in: path
        description: ID of Plan
        required: true
        type: string
        format: string
      - name: itemId
        in: path
        description: ID of Item
        required: true
        type: string
        format: string
      tags:
        - Plan
      responses:
        "200":
          description: Item Added
    delete:
      summary: Single Plan Item Deletion
      parameters:
      - name: planId
        in: path
        description: ID of Plan
        required: true
        type: string
        format: string
      - name: itemId
        in: path
        description: ID of Item
        required: true
        type: string
        format: string
      tags:
        - Plan
      responses:
        "200":
          description: Item Removed

################################################################################
#                                  Promotions                                  #
################################################################################

  /promotion:
    post:
      summary: Promotion Creation.
      parameters:
        - name: promotion
          in: body
          description: Promotion Information
          required: true
          schema:
              $ref: "#/definitions/Promotion"
      responses:
        "201":
          description:  Promotion Created

  /promotion/{promotionId}:
    get:
      summary: Promotion Information
      description:
        Promotion endpoint returns information about the promotion.
      parameters:
        - name: promotionId
          in: path
          description: Promotion
          required: true
          type: string
          format: string
      tags:
        - Promotion
      responses:
        "200":
          description: An Promotion object
          schema:
            $ref: '#/definitions/Promotion'
    put:
      summary: Promotion Modification
      parameters:
      - name: promotionId
        in: path
        description: ID of Promotion
        required: true
        type: string
        format: string
      tags:
        - Promotion
      responses:
        "200":
          description: Promotion Updated
    delete:
      summary: Promotion Deletion
      parameters:
      - name: promotionId
        in: path
        description: ID of Promotion
        required: true
        type: string
        format: string
      tags:
        - Promotion
      responses:
        "204":
          description: Promotion Deleted
         
################################################################################
#                                 Definitions                                  #
################################################################################   
definitions:

  CreateUser:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string

  User:
    type: object
    properties:
      userId:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string

  Location:
    type: object
    properties:
      id: 
        type: string
      name:
        type: string
      address:
        type: string
      city: 
        type: string
      state:
        type: string
      zip: 
        type: string

  Item:
    type: object
    properties:
      id:
        type: string
      name: 
        type: string
      locationId:
        type: string
      prices:
        $ref: '#/definitions/ItemPrice'

  ItemPrice:
    type: object
    properties:
      itemId:
        type: string
      size:
        type: string
      marketPrice:
        type: number
        format: double
      nonMemberPrice:
        type: number
        format: double
      nonMemberCompensationPrice:
        type: number
        format: double
      memberPrice:
        type: number
        format: double
      memberCompensationPrice: 
        type: number
        format: double

  AddOn:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      marketPrice:
        type: number
        format: double
      nonMemberPrice:
        type: number
        format: double
      nonMemberCompensationPrice:
        type: number
        format: double
      memberPrice:
        type: number
        format: double
      memberCompensationPrice: 
        type: number
        format: double

  Plan:
    type: object
    properties:
      id: 
        type: string
      price:
        type: number
        format: double
      duration:
        type: string
      stripePlanId:
        type: string
      category: 
        type: string
      isActive:
        type: boolean
      items:
        type: array
        items:
           title: itemIds
           type: string

  Subscription:
    type: object
    properties:
      id:
        type: string
      userId:
        type: string
      planId:
        type: string
      stripeSubscriptionId:
        type: string
      isActive:
        type: boolean
      startDate: 
        type: string
        format: date-time
      endDate:
        type: string
        format: date-time

  Purchase:
    type: object
    properties:
      id: 
        type: string
      subscriptionId:
        type: string
      itemId: 
        type: array
        items:
           title: itemIds
           type: string
      addOns:
        type: array
        items:
          title: AddOn
          type: object
          properties:
            id:
              type: string
      date:
        type: string
        format: date-time
        
  Promotion:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      code:
        type: string
      type:
        type: string
      category: 
        type: string
      value:
        type: number
      items:
        type: array
        items:
           title: itemIds
           type: string
      startDate: 
        type: string
        format: date-time
      endDate:
        type: string
        format: date-time