swagger: '2.0'

info:
  version: "0.0.1"
  title: BP API
  
basePath: /v1
produces:
  - application/json

paths:
  /user:
      post:
        summary: User Creation.
        responses:
          201:
            description:  User Created
            
  /user/{id}:
      get:
        summary: User Information
        description: |
          The User endpoint returns information about the user.
        parameters:
          - name: id
            in: path
            description: ID of User
            required: true
            type: string
            format: string
        tags:
          - User
        responses:
          200:
            description: A User object
            schema:
              $ref: '#/definitions/User'
      put:
        summary: User Modification
        parameters:
        - name: id
          in: path
          description: ID of User
          required: true
          type: string
          format: string
        tags:
          - User
        responses:
          200:
            description: User Updated
      delete:
        summary: User Modification
        parameters:
        - name: id
          in: path
          description: ID of User
          required: true
          type: string
          format: string
        tags:
          - User
        responses:
          204:
            description: User Deletd
           
         
################################################################################
#                                 Definitions                                  #
################################################################################   
definitions:
  User:
    type: object
    properties:
      userId:
        type: string
