swagger: '2.0'

info:
  version: "0.0.1"
  title: BP API
  
basePath: /v1
produces:
  - application/json

paths:

################################################################################
#                                   Users                                      #
################################################################################ 

  /user:
    post:
      summary: User Creation.
      responses:
        "201":
          description:  User Created
            
  /user/{id}:
    get:
      summary: User Information
      description:
        User endpoint returns information about the user.
      parameters:
        - name: id
          in: path
          description: ID of User
          required: true
          type: string
          format: string
      tags:
        - User
      responses:
        "200":
          description: A User object
          schema:
            $ref: '#/definitions/User'
    put:
      summary: User Modification
      parameters:
      - name: id
        in: path
        description: ID of User
        required: true
        type: string
        format: string
      tags:
        - User
      responses:
        "200":
          description: User Updated
    delete:
      summary: User Modification
      parameters:
      - name: id
        in: path
        description: ID of User
        required: true
        type: string
        format: string
      tags:
        - User
      responses:
        "204":
          description: User Deleted

  /user/{id}/purchase:
    post:
      summary: Purchase For User
      parameters:
      - name: id
        in: path
        description: ID of User
        required: true
        type: string
        format: string
      - name: body
        in: body
        description: Request to process for purchase
        required: true
        schema: 
          $ref: '#/definitions/Purchase'
      responses:
        "201":
          description:  Purchase Successful

  /user/{id}/subscriptions:
    post:
      summary: subscriptions For User
      parameters:
      - name: id
        in: path
        description: ID of User
        required: true
        type: string
      - name: body
        in: body
        description: Request to process for redemption
        required: true
        schema: 
          $ref: '#/definitions/Subscription'
      responses:
        "201":
          description:  Subscription added to User

################################################################################
#                                 Location                                     #
################################################################################ 

  /location:
    post:
      summary: Location Creation.
      responses:
        "201":
          description:  Location Created

  /location/{id}:
    get:
      summary: Location Information
      description:
        Location endpoint returns information about the location.
      parameters:
        - name: id
          in: path
          description: Location
          required: true
          type: string
          format: string
      tags:
        - Location
      responses:
        "200":
          description: An Location object
          schema:
            $ref: '#/definitions/Location'
    put:
      summary: Location Modification
      parameters:
      - name: id
        in: path
        description: ID of Location
        required: true
        type: string
        format: string
      tags:
        - Location
      responses:
        "200":
          description: Location Updated
    delete:
      summary: Location Deletion
      parameters:
      - name: id
        in: path
        description: ID of Location
        required: true
        type: string
        format: string
      tags:
        - Location
      responses:
        "204":
          description: Location Deleted

################################################################################
#                               Location Items                                 #
################################################################################

  /location/{locationId}/items:
    post:
      summary: Item Creation.
      parameters:
        - name: locationId
          in: path
          description: Item
          required: true
          type: string
          format: string
      responses:
        "201":
          description:  Item Created
          schema:
            $ref: '#/definitions/Item'

  /location/{locationId}/items/{id}:
    get:
      summary: Item Information
      description:
        The Item endpoint returns information about the item.
      parameters:
      - name: locationId
        in: path
        description: Item
        required: true
        type: string
        format: string
      - name: id
        in: path
        description: Item
        required: true
        type: string
        format: string
      tags:
        - Item
      responses:
        "200":
          description: An Item object
          schema:
            $ref: '#/definitions/Item'
    put:
      summary: Item Modification
      parameters:
      - name: locationId
        in: path
        description: Item
        required: true
        type: string
        format: string
      - name: id
        in: path
        description: Item
        required: true
        type: string
        format: string
      tags:
        - Item
      responses:
        "200":
          description: Item Updated
    delete:
      summary: Item Deletion
      parameters:
      - name: locationId
        in: path
        description: Item
        required: true
        type: string
        format: string
      - name: id
        in: path
        description: Item
        required: true
        type: string
        format: string
      tags:
        - Item
      responses:
        "204":
          description: Item Deleted

################################################################################
#                             Location AddOn                                   #
################################################################################

  /location/{locationId}/addons:
    get:
      summary: AddOns from a Location
      description:
        The AddOn endpoint returns information about the addons.
      parameters:
      - name: locationId
        in: path
        description: Item
        required: true
        type: string
        format: string
      responses:
        "201":
          description: AddOn Created
          schema:
            $ref: '#/definitions/AddOn'
    post:
      summary: AddOn Creation.
      parameters:
      - name: locationId
        in: path
        description: Item
        required: true
        type: string
        format: string
      responses:
        "201":
          description: AddOn Created
          schema:
            $ref: '#/definitions/AddOn'

  /location/{locationId}/addons/{id}:
    get:
      summary: AddOn Information
      description:
        The AddOn endpoint returns information about the addon.
      parameters:
      - name: locationId
        in: path
        description: Item
        required: true
        type: string
        format: string
      - name: id
        in: path
        description: Item
        required: true
        type: string
        format: string
      tags:
        - AddOn
      responses:
        "200":
          description: An AddOn object
          schema:
            $ref: '#/definitions/AddOn'
    put:
      summary: AddOn Modification
      parameters:
      - name: locationId
        in: path
        description: Item
        required: true
        type: string
        format: string
      - name: id
        in: path
        description: Item
        required: true
        type: string
        format: string
      tags:
        - AddOn
      responses:
        "200":
          description: AddOn Updated
    delete:
      summary: AddOn Deletion
      parameters:
      - name: locationId
        in: path
        description: Item
        required: true
        type: string
        format: string
      - name: id
        in: path
        description: Item
        required: true
        type: string
        format: string
      tags:
        - AddOn
      responses:
        "204":
          description: AddOn Deleted

################################################################################
#                                    Plan                                      #
################################################################################ 

  /plan:
    post:
      summary: Plan Creation.
      responses:
        "201":
          description:  Plan Created

  /plan/{id}:
    get:
      summary: Plan Information
      description:
        The Plan endpoint returns information about the plan.
      parameters:
        - name: id
          in: path
          description: Plan
          required: true
          type: string
          format: string
      tags:
        - Plan
      responses:
        "200":
          description: An Plan object
          schema:
            $ref: '#/definitions/Plan'
    put:
      summary: Plan Modification
      parameters:
      - name: id
        in: path
        description: ID of Plan
        required: true
        type: string
        format: string
      tags:
        - Plan
      responses:
        "200":
          description: Plan Updated
    delete:
      summary: Plan Deletion
      parameters:
      - name: id
        in: path
        description: ID of Plan
        required: true
        type: string
        format: string
      tags:
        - Plan
      responses:
        "204":
          description: Plan Deleted

################################################################################
#                                  Promotions                                  #
################################################################################

  /promotion:
    post:
      summary: Promotion Creation.
      responses:
        "201":
          description:  Promotion Created

  /promotion/{id}:
    get:
      summary: Promotion Information
      description:
        Promotion endpoint returns information about the promotion.
      parameters:
        - name: id
          in: path
          description: Promotion
          required: true
          type: string
          format: string
      tags:
        - Promotion
      responses:
        "200":
          description: An Promotion object
          schema:
            $ref: '#/definitions/Promotion'
    put:
      summary: Promotion Modification
      parameters:
      - name: id
        in: path
        description: ID of Promotion
        required: true
        type: string
        format: string
      tags:
        - Promotion
      responses:
        "200":
          description: Promotion Updated
    delete:
      summary: Promotion Deletion
      parameters:
      - name: id
        in: path
        description: ID of Promotion
        required: true
        type: string
        format: string
      tags:
        - Promotion
      responses:
        "204":
          description: Promotion Deleted
         
################################################################################
#                                 Definitions                                  #
################################################################################   
definitions:

  User:
    type: object
    properties:
      userId:
        type: string
      activeSubscriptions:
        type: array
        items:
          title: activeSubscriptions
          type: object
          properties:
            id:
              type: string

  Location:
    type: object
    properties:
      id: 
        type: string
      name:
        type: string
      address:
        type: string
      city: 
        type: string
      state:
        type: string
      zip: 
        type: string

  Item:
    type: object
    properties:
      id:
        type: string
      name: 
        type: string
      locationId:
        type: string
      marketPrice:
        type: number
        format: double
      nonMemberPrice:
        type: number
        format: double
      nonMemberCompensationPrice:
        type: number
        format: double
      memberPrice:
        type: number
        format: double
      memberCompensationPrice: 
        type: number
        format: double

  AddOn:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      marketPrice:
        type: number
        format: double
      nonMemberPrice:
        type: number
        format: double
      nonMemberCompensationPrice:
        type: number
        format: double
      memberPrice:
        type: number
        format: double
      memberCompensationPrice: 
        type: number
        format: double

  Plan:
    type: object
    properties:
      id: 
        type: string
      userId:
        type: string
    
  Subscription:
    type: object
    properties:
      id:
        type: string
      userId:
        type: string
      planId:
        type: string
      startDate: 
        type: string
        format: date-time
      endDate:
        type: string
        format: date-time

  Purchase:
    type: object
    properties:
      id: 
        type: string
      subscriptionId:
        type: string
      itemId: 
        type: array
        items:
           title: drinkIds
           type: string
      addOns:
        type: array
        items:
          title: AddOn
          type: object
          properties:
            id:
              type: string
      date:
        type: string
        format: date-time
        
  Promotion:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      code:
        type: string
      type:
        type: string
      value:
        type: number
      startDate: 
        type: string
        format: date-time
      endDate:
        type: string
        format: date-time
